'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const invites=read('modules/v107-invites.js');
const integrity=read('modules/registration-integrity-v10_10_9.js');
const firebaseJson=JSON.parse(read('firebase.json'));
const activeRules=String(firebaseJson?.firestore?.rules||'');
const rules=read(activeRules);
const updater=read('update_v10_10_9.js');
const sw=read('sw.js');
const bridge=read('sw_47.js');
const version=JSON.parse(read('version.json'));
function need(v,m){if(!v)throw new Error(m);}
const appCheck=invites.indexOf('await ensureRegistrationAppCheck({forceRefresh:false})');
const invitePrecheck=invites.indexOf("stage='invite-precheck'");
const pause=invites.indexOf('authListenerSuspended=suspendAuthListenerForRegistration()');
const create=invites.indexOf('auth.createUserWithEmailAndPassword(email,pass)');
const token=invites.indexOf('cred.user.getIdTokenResult(true)');
const transaction=invites.indexOf('async function commitRegistration');
const profileWrite=invites.indexOf("transaction.set(db.collection('users').doc(cred.user.uid),userData)");
const inviteWrite=invites.indexOf("transaction.update(inviteRef,{active:false,usedBy:cred.user.uid");
const resume=invites.indexOf('resumeAuthListenerAfterRegistration(authListenerSuspended)');
const updaterBuild=Number(updater.match(/const CURRENT_BUILD=(\d+)/)?.[1]||0);
const workerBuild=Number(sw.match(/const BUILD_REVISION=(\d+)/)?.[1]||0);
const bridgeBuild=Number(bridge.match(/const BUILD_REVISION=(\d+)/)?.[1]||0);
const workerCache=sw.match(/const CACHE_HOTFIX='([^']+)'/)?.[1]||'';
const bridgeCache=bridge.match(/const CACHE_HOTFIX='([^']+)'/)?.[1]||'';
need(activeRules==='firebase/firestore_28_compacto.rules','Cadastro deve ser validado contra a Rules 28 ativa.');
need(appCheck>=0&&invitePrecheck>appCheck&&create>invitePrecheck,'App Check e convite devem ser validados antes da criação Auth quando o preflight público estiver disponível.');
need(invites.includes("withTimeout(initOptionalAppCheck(),8000,'App Check do cadastro')"),'Cadastro deve ter orçamento próprio de 8 s e não herdar o timeout curto do boot.');
need(invites.includes('service.getToken(!!forceRefresh)'),'Validação App Check deve escolher explicitamente entre token válido em cache e refresh forçado.');
need(invites.includes('await ensureRegistrationAppCheck({forceRefresh:false})'),'Primeiro preflight deve aceitar token App Check válido já persistido e deixar o SDK renovar apenas se necessário.');
need(invites.includes('await ensureRegistrationAppCheck({forceRefresh:true})'),'Recuperação de permission-denied da transação deve forçar um token App Check novo antes do único retry.');
need(invites.includes("doRegister.__tbRegistrationAppCheck='cached-first'"),'Fluxo canônico deve expor a política App Check cached-first para diagnóstico de produção.');
need(invites.includes("error.code='team-bulls/app-check-failed'"),'Falha de App Check precisa possuir código próprio e não virar permission-denied genérico.');
need(invites.includes("precheckRequiresAuth=true"),'Permission denied no preflight precisa migrar para revalidação autenticada sem consumir o convite.');
need(invites.includes("stage='invite-auth-check'"),'O convite precisa ser revalidado depois do Auth quando a Rules publicada negar o preflight anônimo.');
need(invites.includes("stage='transaction-refresh'"),'Permission denied da transação deve renovar credenciais antes de uma única repetição.');
need(invites.includes("await commitRegistration(inviteRef,cred,userData)"),'A transação protegida deve usar uma função única para evitar divergência entre primeira tentativa e retry.');
need(invites.includes('[REG-FS-403]'),'Permission denied final da transação deve possuir diagnóstico estável REG-FS-403.');
need(invites.includes("window.TeamBullsRegistrationDiagnostics=registrationDiagnostic"),'Diagnóstico seguro da última etapa deve ficar disponível sem expor e-mail, senha ou convite.');
need(pause>=0&&create>pause,'O observador de autenticação deve ser pausado antes de criar a conta Auth.');
need(token>create&&transaction>=0,'A credencial Auth deve ser renovada e a transação canônica deve existir.');
need(invites.includes("tokenResult?.claims?.email||cred.user.email"),'O perfil deve usar o e-mail canônico do token Auth para corresponder literalmente às Rules.');
need(profileWrite>transaction&&inviteWrite>profileWrite,'Perfil e consumo do convite devem permanecer na mesma transação.');
need(resume>profileWrite,'O observador só pode voltar depois da janela crítica do cadastro.');
need(invites.includes("if(typeof AUTH_UNSUBSCRIBE==='function')"),'A pausa precisa usar o unsubscribe já controlado pelo núcleo.');
need(invites.includes("if(typeof startAuthListener==='function')startAuthListener()"),'O observador precisa ser restaurado pelo inicializador oficial.');
need(invites.includes('doRegister.__tbCanonicalInviteRegistration=true'),'O fluxo canônico precisa ser identificado explicitamente.');
need(invites.includes("doRegister.__tbRegistrationPreflight=REGISTRATION_DIAGNOSTIC_REVISION"),'A revisão de preflight deve ser identificável em produção.');
need(invites.includes("REGISTRATION_DIAGNOSTIC_REVISION='preflight3'"),'A revisão resiliente do cadastro mobile precisa estar ativa.');
need(invites.includes("window.addEventListener('team-bulls-runtime-state',enforceCanonicalRegistration)"),'O cadastro seguro deve se restaurar após cada módulo diferido.');
need(!integrity.includes('doRegister=secured'),'A camada de integridade não pode mais substituir doRegister.');
need(integrity.includes("const VERSION='10.10.9-registration2'"),'A revisão passiva da integridade do cadastro precisa estar ativa.');
need(rules.includes('match /studentInvites/{id}'),'As Rules ativas precisam conter a coleção de convites.');
need(rules.includes('allow get: if true;'),'O preflight público deve continuar restrito a get de um convite hash, nunca listagem pública.');
need(rules.includes("getAfter(/databases/$(database)/documents/studentInvites/$(request.resource.data.inviteId)).data.usedBy == uid"),'A criação do aluno deve continuar dependente do convite consumido atomicamente.');
need(rules.includes("getAfter(/databases/$(database)/documents/users/$(request.auth.uid)).data.inviteId == id"),'O consumo do convite deve continuar vinculado ao perfil do mesmo UID.');
need(updaterBuild===version.build&&workerBuild===version.build&&bridgeBuild===version.build,'Build do cadastro precisa ser idêntico no endpoint, atualizador e dois Service Workers.');
need(updater.includes("./modules/registration-integrity-v10_10_9.js?v=10.10.9-registration2"),'Atualizador deve renovar explicitamente a integridade do cadastro.');
need(workerCache&&workerCache===bridgeCache,'A release precisa manter os caches coerentes nos dois Service Workers.');
need(sw.includes("./modules/registration-integrity-v10_10_9.js?v=10.10.9-registration2")&&bridge.includes("./modules/registration-integrity-v10_10_9.js?v=10.10.9-registration2"),'Service Workers não podem preparar a revisão registration1 antiga.');
console.log(`APROVADO: cadastro por convite, App Check cached-first com refresh forçado apenas na recuperação 403, atomicidade e build ${version.build} seguem coerentes sob ${activeRules}.`);
